-- Fase 29C - Pedidos Hoy y corrección de clientes crédito
-- No crea tablas nuevas. Esta fase usa las tablas existentes:
--   public.pedidos
--   public.clientes_credito
--   public.cartera_movimientos
--
-- Objetivo de la fase:
-- 1. Visualizar de forma más clara la forma de pago en Pedidos Hoy.
-- 2. Permitir corregir el nombre del cliente crédito desde Pedidos Hoy.
-- 3. Mover el movimiento de cartera del pedido corregido al cliente crédito correcto.
-- 4. Recalcular saldo pendiente, total de pedidos y último pedido del cliente anterior y del nuevo cliente.
--
-- Este archivo queda como respaldo de control de versión para Supabase.
