import { useEffect, useState } from "react";
import { listarUsuariosRoles, actualizarRolUsuario, actualizarEstadoUsuario } from "../../../services/usuariosRolesService";
import { crearCuentaAdmin, restablecerClaveAdmin } from "../../../services/adminUsersService";

export default function UsuariosPermisosAjustes() {
  const [usuarios, setUsuarios] = useState([]); const [cargando, setCargando] = useState(true); const [mensaje, setMensaje] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [rolNuevo, setRolNuevo] = useState("usuario");
  async function cargar() { setCargando(true); try { setUsuarios(await listarUsuariosRoles()); setMensaje(""); } catch (e) { setMensaje(e?.message || "No se pudieron cargar las cuentas actuales."); } finally { setCargando(false); } }
  useEffect(() => { cargar(); }, []);
  async function cambiarRol(usuario, rol) { try { const actualizado = await actualizarRolUsuario(usuario.id, rol); setUsuarios((actual) => actual.map((item) => item.id === usuario.id ? { ...item, ...actualizado } : item)); setMensaje("Rol actualizado correctamente."); } catch (e) { setMensaje(e?.message || "No se pudo actualizar el rol."); } }
  async function cambiarEstado(usuario) { try { const actualizado = await actualizarEstadoUsuario(usuario.id, usuario.activo === false); setUsuarios((actual) => actual.map((item) => item.id === usuario.id ? { ...item, ...actualizado } : item)); setMensaje("Estado de la cuenta actualizado."); } catch (e) { setMensaje(e?.message || "No se pudo actualizar el estado."); } }
  async function crear() { try { if (!email || password.length < 8) throw new Error("Ingresa un correo y una contraseña de mínimo 8 caracteres."); await crearCuentaAdmin(email, password, rolNuevo); setEmail(""); setPassword(""); setMensaje("Cuenta creada correctamente."); await cargar(); } catch (e) { setMensaje(e?.message || "No se pudo crear la cuenta."); } }
  async function restablecer(usuario) { const nueva = window.prompt(`Nueva contraseña para ${usuario.email} (mínimo 8 caracteres):`); if (!nueva) return; try { await restablecerClaveAdmin(usuario.user_id, nueva); setMensaje("Contraseña restablecida correctamente."); } catch (e) { setMensaje(e?.message || "No se pudo restablecer la contraseña."); } }
  return <div className="box soft" style={{ marginTop: 14 }}><div className="section-heading"><div><strong>👤 Usuarios y permisos</strong><p className="muted small">Cuentas actuales registradas en Supabase. Se conservan sus accesos e historial.</p></div><button type="button" className="button light" onClick={cargar}>Actualizar</button></div><div className="box" style={{ margin: "12px 0" }}><strong>Crear cuenta</strong><div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 8 }}><input type="email" placeholder="Correo" value={email} onChange={(e) => setEmail(e.target.value)} /><input type="password" placeholder="Contraseña" value={password} onChange={(e) => setPassword(e.target.value)} /><select value={rolNuevo} onChange={(e) => setRolNuevo(e.target.value)}><option value="usuario">Usuario</option><option value="admin">Administrador</option></select><button type="button" className="button" onClick={crear}>Crear cuenta</button></div></div>{mensaje && <p className="muted small">{mensaje}</p>}{cargando ? <p>Cargando cuentas actuales...</p> : <div style={{ overflowX: "auto" }}><table className="control-cantidades-tabla"><thead><tr><th>Correo</th><th>Rol</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{usuarios.map((usuario) => <tr key={usuario.id || usuario.email}><td>{usuario.email}</td><td><select value={usuario.rol || "usuario"} onChange={(e) => cambiarRol(usuario, e.target.value)}><option value="admin">Administrador</option><option value="usuario">Usuario</option></select></td><td>{usuario.activo === false ? "Inactiva" : "Activa"}</td><td><button type="button" className="button light" onClick={() => cambiarEstado(usuario)}>{usuario.activo === false ? "Activar" : "Desactivar"}</button><button type="button" className="button light" onClick={() => restablecer(usuario)}>Restablecer clave</button></td></tr>)}</tbody></table></div>}</div>;
}
